---

- name: install misc
  apt:
    name: "{{ item }}"
    state: present
  with_items:
    - bash-completion
    - curl
    - git
    - memcached
    - nano
    - php-pear
    - wget

- name: install php
  apt:
    name: "{{ item }}"
    state: present
  with_items:
    - libapache2-mod-php5
    - php5
    - php5-curl

- name: make sure apache is running
  service: name=apache2 state=started enabled=true

- name: install mysql
  apt:
    name: "{{ item }}"
    state: present
  with_items:
    - libapache2-mod-auth-mysql
    - mysql-client
    - mysql-server
    - php5-mysql

- name: make sure mysql is running
  service: name=mysql state=started enabled=true

- name: install memcache
  command: pecl install memcache

- name: add drush channel
  command: pear channel-discover pear.drush.org
  ignore_errors: yes

- name: install drush
  command: pear install drush/drush
  ignore_errors: yes
